### ISSUE TITLE
[Bug]: Not working with locally deployed broker

### ISSUE THREAD

**Issue by himoacs** [appronto/Solace-browser-extension#19]
### Bug Description

The extension doesn't work with non-solace cloud deployments such as a locally deployed broker running on localhost:1943.
Gives the following error:

> For the Message VPN URL filed, please use a URL matching https://{{your_domain}}.messaging.solace.cloud:943

### Expected Behavior

Expected behavior would be for the extension to accept URL for local broker like it does for Solace Cloud broker.

### Steps to Reproduce

Steps to reproduce: Deploy a broker locally via docker/podman.

**Comment by philll11** [comment]
Hi @himoacs, thank you for raising this bug. I have deployed a fix to [19-bug-not-working-with-locally-deployed-broker](https://github.com/solacecommunity/solace-queue-browser-extension/tree/19-bug-not-working-with-locally-deployed-broker). Would it be possible to test the fix on your machine?
